---
driver:
  name: docker
  require_chef_omnibus: true
  customize:
    memory: 1024

provisioner:
  name: chef_zero
  attributes:
    java:
      ark_retries: 2
      ark_retry_delay: 10

platforms:
  - name: ubuntu-16.04
  - name: debian-8.6
  - name: centos-7.3

suites:
  - name: artifactory-oracle
    run_list:
      - recipe[artifactory]
    attributes:
      java:
        oracle:
          accept_oracle_download_terms: true
        install_flavor: oracle
