version: 2
jobs:
  test:
    docker:
      - image: chef/chefdk
    working_directory: ~/chef-repo
    steps:
      - checkout
      - run:
          name: running foodcritic
          command: |
            foodcritic .
      - run:
          name: running cookstyle
          command: |
            cookstyle
  integration:
    machine: true
    # docker:
    #  - image: chef/chefdk
    working_directory: ~/chef-repo
    steps:
      - checkout
      # - run:
      #     name: Install docker
      #     command: |
      #       apt-get update --fix-missing
      #       apt-get install -y apt-transport-https ca-certificates software-properties-common
      #       curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
      #       apt-key fingerprint 0EBFCD88
      #       add-apt-repository \
      #         "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
      #         $(lsb_release -cs) \
      #         stable"
      #       apt-get update
      #       apt-get install -y docker-ce
      #       docker --version
      #       service start docker
      # - run:
      #     name: Install docker
      #     command: |
      #       sudo apt-get update --fix-missing
      #       sudo apt-get install -y apt-transport-https ca-certificates software-properties-common
      #       curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      #       sudo apt-key fingerprint 0EBFCD88
      #       sudo add-apt-repository \
      #         "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
      #         $(lsb_release -cs) \
      #         stable"
      #       sudo apt-get update
      #       sudo apt-get install -y docker-ce
      #       docker --version
      - run:
          name: Install chefdk
          command: |
            sudo apt-get update --fix-missing
            sudo apt-get install -y apt-transport-https
            wget -qO - https://packages.chef.io/chef.asc | sudo apt-key add -
            echo "deb https://packages.chef.io/repos/apt/stable $(lsb_release -cs) main" > /etc/apt/sources.list.d/chef.list
            sudo apt-get update
            sudo apt-get install -y chefdk
            docker --version
            chef --version
            eval "$(chef shell-init bash)"
      - run:
          name: adding kitchen-docker
          command: |
            chef gem install kitchen-docker
      - run:
          name: running kitchen create
          command: |
            kitchen create -c
      - run:
          name: destroying kitchen
          command: |
            kitchen destroy
workflows:
  version: 2
  base:
    jobs:
    - test
    - integration
  nightly:
    jobs:
      - test
    triggers:
      -
        schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
