version: 2
jobs:
  linting:
    docker:
      - image: chef/chefdk
    working_directory: ~/chef-repo
    steps:
      - checkout
      - run:
          name: running foodcritic
          command: |
            foodcritic .
      - run:
          name: running cookstyle
          command: |
            cookstyle
  integration:
    machine: true
    # docker:
    #   - image: chef/chefdk
    working_directory: ~/chef-repo
    steps:
      - checkout
      - run:
          name: Install chefdk
          command: |
            sudo apt-get update --fix-missing
            sudo apt-get install -y apt-transport-https
            wget -qO - https://packages.chef.io/chef.asc | sudo apt-key add -
            echo "deb https://packages.chef.io/repos/apt/stable $(lsb_release -cs) main" > chef.list
            sudo mv chef.list /etc/apt/sources.list.d/
            sudo apt-get update
            sudo apt-get install -y chefdk
            docker --version
            chef --version
            eval "$(chef shell-init bash)"
      - run:
          name: adding kitchen-dokken
          command: |
            chef gem install kitchen-dokken
      - run:
          name: running kitchen create
          command: |
            kitchen test -c 3
      - run:
          name: destroying kitchen
          command: |
            kitchen destroy
workflows:
  version: 2
  base:
    jobs:
    - linting
    - integration
  nightly:
    jobs:
      - linting
      - integration
    triggers:
      -
        schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
