version: 2
jobs:
  test:
    docker:
      - image: chef/chefdk
    working_directory: ~/chef-repo
    steps:
      - checkout
      - run:
          name: running foodcritic
          command: |
            foodcritic .
      - run:
          name: running cookstyle
          command: |
            cookstyle
  integration:
    machine: true
    # docker:
    #   - image: chef/chefdk
    working_directory: ~/chef-repo
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common -y
      - run: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
      - run: apt-key fingerprint 0EBFCD88
      - run: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      - run: apt-get update
      - run: apt-get install docker-ce docker-ce-cli containerd.io -y
      - run:
          name: adding kitchen-docker
          command: |
            chef gem install kitchen-docker
      - run:
          name: running kitchen create
          command: |
            kitchen create -c
      - run:
          name: destroying kitchen
          command: |
            kitchen destroy
workflows:
  version: 2
  base:
    jobs:
    - test
    - integration
  nightly:
    jobs:
      - test
    triggers:
      -
        schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
