version: 2
jobs:
  test:
    docker:
      - image: chef/chefdk
    working_directory: ~/chef-repo
    steps:
      - checkout
      - run:
          name: running foodcritic
          command: |
            foodcritic .
      - run:
          name: running cookstyle
          command: |
            cookstyle
workflows:
  version: 2
  base:
    jobs:
    - test
  nightly:
    jobs:
      - test
    triggers:
      -
        schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
